// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
          apiKey: "AIzaSyB9lNGzfsyORNEYF6zuFaZ-4ZMHR-uHTgY",
          authDomain: "deliveryapp2705.firebaseapp.com",
          databaseURL: "https://deliveryapp2705-default-rtdb.firebaseio.com",
          projectId: "deliveryapp2705",
          storageBucket: "deliveryapp2705.appspot.com",
          messagingSenderId: "598180524456",
          appId: "1:598180524456:web:4774bb73b2f1ad5245ed9d",
  
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpKJZayUFuwdpsATIOLuYjGou3znRWWmg',
    appId: '1:569132697787:android:cc8223b1f5c68491ff819e',
    messagingSenderId: '569132697787',
    projectId: 'deliveryapp-ac3db',
    databaseURL: 'https://deliveryapp-ac3db-default-rtdb.firebaseio.com',
    storageBucket: 'deliveryapp-ac3db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTzTJoxLE6oBeUw_1x1a05ktRjkWfnGOs',
    appId: '1:569132697787:ios:9fe47d1be1b034bcff819e',
    messagingSenderId: '569132697787',
    projectId: 'deliveryapp-ac3db',
    databaseURL: 'https://deliveryapp-ac3db-default-rtdb.firebaseio.com',
    storageBucket: 'deliveryapp-ac3db.appspot.com',
    iosClientId: '569132697787-kjr7gtgkueern4k1uifranrerk8vtqkb.apps.googleusercontent.com',
    iosBundleId: 'com.example.clickCounter',
  );
}
